### ISSUE TITLE
[REQUEST] Add Mastodon Share Button

### ISSUE THREAD

**Issue by retiolus** [adityatelange/hugo-PaperMod#1189]

**Comment by mustafaalbazy** [comment]
I have added the Mastodon share button in the latest pull request. Until they review it and approve it, you can copy it straightaway on your site/blog if you wish. 

#1240

**Comment by besendorf** [comment]
@retiolus the PR is still open but the issue is closed. Could you reopen the issue until the PR is merged?

**Comment by adityatelange** [comment]
TL;DR It can't be implemented with ease.

This could not be added as mastodon is a decentralized social media. An instance needs to be chosen 1st then a link can be created to post it. It more difficult to implement a share button that works consistently across all Mastodon instances.

About the PR, it only mentions `mastodon.social` and it will ask you to sign-in in order to share the link instead of choosing the instance. 
![image](https://github.com/adityatelange/hugo-PaperMod/assets/21258296/bef1e219-d281-4305-8407-ac90b92fa63b)

**Comment by besendorf** [comment]
You could just use this solution: https://aly-ve.github.io/Mastodon-share-button/
It asks the user for their Mastodon Server and optionally saves their server.
