### ISSUE TITLE
 Issue with Language Switching on Hugo Blog Using OpenAI Theme

### ISSUE THREAD

**Issue by cubxxw** [adityatelange/hugo-PaperMod#1315]
**Description:**
I am encountering an issue on my Hugo blog, which is hosted at nsddd.top and uses your OpenAI theme. The problem I'm facing is related to language switching. Whenever I try to switch to a different language within my articles or other sections of the website, it redirects me to the homepage. This issue doesn't occur with other themes, and I'm unsure why it's happening with your theme.

**Request for Assistance:**
I sincerely request your assistance in diagnosing and resolving this issue. I would appreciate it if you could provide guidance on how to fix this problem or suggest any configuration changes that might be necessary to enable smooth language switching while using your theme.

My blog environment： [https://nsddd.top](https://nsddd.top)

Thank you for your attention and support. Your help in resolving this issue would be greatly appreciated.

**Comment by HarisDotParis** [comment]
This is related to issue #1065 and pull request #1159.

The repo maintainer thinks this should be default behaviour. Only the "Translations" links under each post (which you already enabled) redirect directly to the post's translation. The language links at the top of the page will always redirect to each language's homepage.

I have proposed changing that so that the language links at the top redirect to the translated post or page, but the maintainer disagrees this makes more sense. @adityatelange I hope you have changed your mind or we can find some other solution to make this work. I know maintaining this repo takes quite some effort, but I hope we can resolve this.

**Comment by adityatelange** [comment]
Not OpenAI theme. dup of #1065
