### ISSUE TITLE
Links are not highlighted in latest release

### ISSUE THREAD

**Issue by sbunzel** [adityatelange/hugo-PaperMod#189]
Thanks for the great theme! I started using it two weeks ago and love it.

I just noticed that between [dd83560](https://github.com/adityatelange/hugo-PaperMod/commit/dd835600104d051ebaf591658939ab131c5ff494) (the version I was using and [release 4.0](https://github.com/adityatelange/hugo-PaperMod/releases/tag/v4.0), highlighting of links seems to have been removed. See [this section](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#accesskeys) of the example site:

![image](https://user-images.githubusercontent.com/37472614/105576293-1848a100-5d72-11eb-9671-7b109486517f.png)

(There's a link behind "What's AccessKeys?")

Is this on purpose? If yes, could you point me to the section of the theme I need to customize to customize this? :)

Steffen

**Comment by adityatelange** [comment]
Yes I am aware of this issue, is not intentional.

The issue is weird, coz on some devices like on my desktop browser which is chrome, 
similar one was https://github.com/adityatelange/hugo-PaperMod/commit/042f4e9254450bf03792b3b1e2f359922a8339c4#commitcomment-46225155

![image](https://user-images.githubusercontent.com/21258296/105576857-b43ad280-5d9b-11eb-9538-2a58b566119a.png)

**Comment by adityatelange** [comment]
@sbunzel Sorry for bad experience, let me know if it isn't fixed

**Comment by sbunzel** [comment]
Works, thanks @adityatelange!
