### ISSUE TITLE
Usage of absolute URLs

### ISSUE THREAD

**Issue by fkohrt** [adityatelange/hugo-PaperMod#208]
Is there a specific reason that PaperMod uses `absLangURL` instead of `relLangURL` to create links in the menu? Using relative URLs would allow for easier continuous integration in cases where the site is temporarily deployed to random subdirectories (as with GitLab assets). I propose changing the following occurences:

https://github.com/adityatelange/hugo-PaperMod/blob/b4933eadd65f922cad20e5f9da68ef645564ebfe/layouts/partials/header.html#L53

https://github.com/adityatelange/hugo-PaperMod/blob/b4933eadd65f922cad20e5f9da68ef645564ebfe/layouts/partials/header.html#L112-L116

https://github.com/adityatelange/hugo-PaperMod/blob/e1ea90aa60acdf150f4b112211649364e3c55c65/layouts/partials/footer.html#L5

**Comment by kdkasad** [comment]
I agree with this. It makes it easier for local testing using `hugo
server` as well.

**Comment by adityatelange** [comment]
Use of absolute URLs is fairly better for SEO,
- relative urls are better for browsers not bots
- using absolute url prevents breaking of webpages when using proxies as the resource is always fetched from `baseURL`
- Embedding webpages break when using relative urls
-  absolute url will use `https` to fetch the resource, or the browser will always try to fetch from http 1st then shift to https if the server tells the browser to ..

Only the Asssets aren't being generated as absoute url because of https://git.io/Jtlx5

**Comment by adityatelange** [comment]
I do agree that this can be given as choice as `canonifyURLs` is a option provided by hugo

**Comment by fkohrt** [comment]
@adityatelange so can this be merged?

**Comment by adityatelange** [comment]
> @adityatelange so can this be merged?

maybe not

**Comment by fkohrt** [comment]
Can #212 be improved or you generally against it?

**Comment by adityatelange** [comment]
> Can #212 be improved or you generally against it?

I see the pagination breaks, also there are other unrelated commits with it and conflicts should be fixed

**Comment by fkohrt** [comment]
> there are other unrelated commits

Right, I only noticed this now.
