### ISSUE TITLE
Can not use images in Markdown document

### ISSUE THREAD

**Issue by jonimofo** [adityatelange/hugo-PaperMod#214]
Hello,

I really love this theme and would like to use it for my student projects. However, I am really struggling with the use of images in Markdown documents.

I am using the traditionnal Markdown format for calling images, such as ` ![aLt text](path/to/image)`
I tried a lot of different combinaisons for referencing an image ` ![](/static/imagename)`  for instance but sadly I could never make it work. It does work with images that are hosted on other websites though.

My repo can be publicly accessible here : https://gitlab.com/jonimofo/hugo-pandas/-/tree/master

and is deployed here : https://jonimofo.gitlab.io/hugo-pandas/posts/test/

If you look at **the article named test**, you can see that a cover image works but it does not work when I try to insert an image within the article. Any help would be greatly appreciated !

Oh and once again, congrats for this awesome theme, I can not wait to use it properly !
(Also I hope this issue reporting is good as I have never done that before, so my apologies if this is not correct !).

**Comment by Jippay** [comment]
Hello,
it is necessary to put the extension of the image file (.jpg .png ...)
and don't bother to put /static/

For example, my image is placed like this:
static/images/myimage.jpg

And I call it this:
![img1](/images/myimage.png)

**Comment by Jippay** [comment]
Hello,
it is necessary to put the extension of the image file (.jpg .png ...)
and don't bother to put /static/

For example, my image is placed like this:
static/images/myimage.jpg

And I call it this:
`![img1](/images/titredemonimage.png) `

**Comment by joelouthan** [comment]
@Jippay Do you have to set the images directory under [params] like so:

```
[params]
    images: ["/static/images/"]
```

**Comment by adityatelange** [comment]
@jonimofo I've tried this myself, and I am also confused why that is not working in any combination. 
This should be issue because of having a subfolder in the baseURL(https://example.com/subdir/) and not only domain (https://example.com/).
It seems to be a bug in hugo itself, as PaperMod does not modify any markdown images. 

Maybe you should head over to hugo's issue tracker here: https://github.com/gohugoio/hugo/issues, but there are a lot of issues already which are stale enough, idk when it will get resolved or priority it will be given ..

What I suggest you as a work around is that use page bundles : https://gohugo.io/content-management/page-bundles/
as images are loading correctly with page bundles in PaperMod's demo

**Comment by jonimofo** [comment]
Thanks everybody for your replies and everyone for your help !
@adityatelange I somehow managed to finally make it work. I have to use it like this : `![](../../cicd.png#center)`.
However, when I have to reference an image for a post cover, i have to do it like this : 
```yml
cover:
    image: hugo_logo.jpg
```
Otherwise it does not work !

My problem is now solve but this still remains a mystery for me !
