### ISSUE TITLE
[Discussion]Meta Tags for better Social Sharing of posts.

### ISSUE THREAD

**Issue by aghdom** [adityatelange/hugo-PaperMod#30]
How would you feel about adding `meta` tags for various social networks to the `head.html` partial to make the shared posts better looking? 
The theme already supports easy sharing using the buttons, it would be nice to have the posts also look good on social media.

It should be a relatively easy addtion. (Here's an example of the tags for Twitter and Facebook): 
```html
<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://example.com/">
<meta property="og:title" content="Post Title">
<meta property="og:description" content="Post Description">
<meta property="og:image" content="<cover-image-url>">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://example.com/">
<meta property="twitter:title" content="Post Title">
<meta property="twitter:description" content="Post Description">
<meta property="twitter:image" content="<cove-image-url>">

```

**Comment by adityatelange** [comment]
Hello @aghdom,
We already have implemented og, twitter cards, one need to set `env` to production as mentioned in code below.
https://github.com/adityatelange/hugo-PaperMod/blob/2c7cffb617dd925d1e69432a34f6987314c2b8c1/layouts/partials/head.html#L50-L55

However the cover image linking is already under discussion https://github.com/adityatelange/hugo-PaperMod/issues/13#issuecomment-705313991

The linked pull-request https://github.com/adityatelange/hugo-PaperMod/pull/31 will add _duplicate_ code to the head section, we need more better implementation by overriding the hugo's internal template for both og as well as twitter-cards.

**Comment by adityatelange** [comment]
I have added stuff for this change =>  https://github.com/adityatelange/hugo-PaperMod/compare/6c4e094c91ce%5E...306889f68bcb
But I am unsure if this needs to be merged :thinking: 

Hugo has a way to include the image in `images` 

ref : https://github.com/gohugoio/hugo/blob/e9a7ebaf67a63ffe5e64c3b3aaefe66feb7f1868/tpl/tplimpl/embedded/templates/opengraph.html#L5-L16

It can be used in social meta just by adding `cover` or `thumbnail` in its name and it will show up :tada: 

---

> this won't work as hugo's (opengraph and twitter)'s template doesn't support relative urls, and I cannot fix that

Ah damn! that's disappointing. Looks like there are some fixes scattered on the internet. I'll try these

1. https://discourse.gohugo.io/t/links-for-images-videos-audio-in-internal-templates-twitter-cards-and-opengraph/10464
2. https://discourse.gohugo.io/t/how-to-set-open-graph-image-for-a-specific-page/6700/6
3. https://www.telematika.org/post/adjusting-hugo-internal-open-graph-template/

_Originally posted by @singhkays in https://github.com/adityatelange/hugo-PaperMod/issues/13#issuecomment-705320038_


@adityatelange The first link worked perfectly! I'll close this but you should think about implementing this in the theme by default. I can see the value add of specifying one of the images in the blog post as one of the OG or Twitter card images rather than storing these in a separate folder and then specifying the absolute path.

_Originally posted by @singhkays in https://github.com/adityatelange/hugo-PaperMod/issues/13#issuecomment-705838942_

---

cc @aghdom @singhkays @kdkasad

**Comment by aghdom** [comment]
Thank you for the info! I had no idea this was a thing, because I worked with Hugo a long time ago and didn't keep up with the new changes. 

The benefit of adding the custom templates, which would allow you to use the `cover.image` is that you wouldn't need to specify the image in two separate places, so for the sake of convenience I think it would still be worth merging.

Of course the other side of that coin is the fact that if you introduce this template you will need to keep it up to date with the changes made to the `_internal` template, if you want to keep all the new funcionality/changes they add.

Ultimately, it's up to you, whether you choose to add it or not. Since I now know how to specify it using the base Hugo template, I can update my posts to work correctly, if you choose not to merge it.

And once again a huge thanks for taking the time and sharing this information with me! :pray: You, sir, rock! :metal:

**Comment by adityatelange** [comment]
The thing is I've tested the code with and without having template override the cover link needs to be with other params of twitter cards or same with opengraph, otherwise it would choose the image that is near to other params will be selected 

So I think it should be replaced with _internal ones
