### ISSUE TITLE
[BUG] ShowShareButtons option in post doesn't work

### ISSUE THREAD

**Issue by ODIRFY** [adityatelange/hugo-PaperMod#327]
If I try to deactivate the share buttons (for example in the privacy policy), the buttons are still displayed.

If I deactivate it with "ShowShareButtons: false" in the config, the share Buttons are not displayed. but in a **post** the Share Buttons are always displayed, when I want to disable it for the about page / Privacy Policy etc.

**Comment by adityatelange** [comment]
I don't think this is a bug, in case you have missed it 
https://github.com/adityatelange/hugo-PaperMod/wiki/Variables here are all vars you can use with PaperMod, 
I have done a mistake here instead of using already existing var i.e. `ShowShareButtons` I've added a new one `disableShare` for front-matter vars. Now that it is included, people are using it and I don't want to remove it from theme.
So... you can use `disableShare = true` to disable share buttons for a particular post.

**Comment by ODIRFY** [comment]
You are right, thank you!
