### ISSUE TITLE
Reading time always 1 min where the content is in Mandarin 

### ISSUE THREAD

**Issue by Ayaoayao** [adityatelange/hugo-PaperMod#402]
Hi there, 
I am trying to write content in Mandarin. Everything looks good to me and the translation is good as well.
The `read_time` can be translated into `分钟` according to [this yaml](https://github.com/adityatelange/hugo-PaperMod/blob/master/i18n/zh.yaml) etc.

On the other hand, the post always shows suggested reading time as 1 min no matter how long the content is.
![image](https://user-images.githubusercontent.com/33715994/117526510-4471f000-aff8-11eb-97a7-2361aa6f8e7a.png)

Could you help me identify this problem? Please let me know if you would like some Mandarin content.

**Comment by harwck** [comment]
Try adding "defaultContentLanguage = "zh"" in your config.toml.
This worked for me.

**Comment by Ayaoayao** [comment]
@harwck Thanks for your suggestion, this will translate the `min` into `分钟`
On the other hand, the actual minutes that need to take are not correct. 
Even I paste thousands of Chinese charters, it still shows 1 `分钟` though.

**Comment by harwck** [comment]
As for the reading time, please check the Hugo documentation here: https://gohugo.io/getting-started/configuration/#all-configuration-settings
and add the "hasCJKLanguage = true" to your config so that Hugo can automatically detect the Chinese, Korean, Japanese in your articles for generating the correct reading time.

**Comment by Ayaoayao** [comment]
> hasCJKLanguage

Thanks! That works for me
