### ISSUE TITLE
[Feature] Please add cusdis for the default comment system

### ISSUE THREAD

**Issue by qvieth** [adityatelange/hugo-PaperMod#653]
https://github.com/djyde/cusdis

![image](https://user-images.githubusercontent.com/71810726/144041297-9459ec6d-7d6c-4737-8e03-053fa9795a93.png)

As I struggle looking for how to make Cusdis changing light and dark mode function to work with Papermod, I just thought about suggesting adding this awesome comment system for the default comment system of Papermod. Cusdis is free also the design of it I think it fit really well with PaperMod. Please consider this idea!!

**Comment by nielsbrakel** [comment]
Really like Cusdis. In my own PaperMod blog I already created a partial with needed config options for Cusdis to work, but there is currently a problem with the theme switching I opened a [new issue](https://github.com/djyde/cusdis/issues/170) for this and when I can will try to fix it myself but until then I would just wait. If this issue is fixed I will open a PR for my partial so everyone can enjoy it.

**Comment by adityatelange** [comment]
Hello @qvieth sorry for keeping you waiting for so long, it will be up to users what comment system they would like to use.
As we are not affiliated with any of them, this will be as it is. we might add it in the future but for now, no plans.
