### ISSUE TITLE
found no layout file for "HTML"

### ISSUE THREAD

**Issue by janhenckens** [adityatelange/hugo-PaperMod#70]
Hey! Trying to set up a new site with this theme and I get a bunch of warnings that don't appear to be covered in the install instructions:

`WARN 2020/11/05 10:02:50 found no layout file for "HTML" for layout "archives" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`

`
WARN 2020/11/05 10:02:50 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
`

And the same for a bunch of other page types (tags, home, post).
I'm pretty new to Hugo but I haven't run into this in the other 2 sites I've build with it.

Am I missing something obvious? Thanks :)

**Comment by adityatelange** [comment]
Hey @janhenckens ,

I have tested a new site with config.yml and instructions mentioned at https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/

but it went all good.

---

Are you using your previous theme's config ? 

Can you share the source you are using ? so that I can see whether something needs to be changed ..

You can also refer to exampleSite here https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite and check whether you are missing something

**Comment by exen904** [comment]
I had the same issue at first, it seems like hugo creates a `hugo.toml ` also when setting up a new site with YAML format. After the file gets deleted, everything works as it should
