### ISSUE TITLE
configurable dark/light image variants

### ISSUE THREAD

**Issue by MyriaCore** [adityatelange/hugo-PaperMod#77]
Anytime an image url is specified in the config, it should be possible to allow a dark and light variant of that asset to be specified, so when the user switches themes, the asset can be switched as well.

**Comment by adityatelange** [comment]
Image is an image, why would anyone put dark/light variants ? Doesn't seem any useful.

**Comment by kdkasad** [comment]
> Image is an image, why would anyone put dark/light variants ? Doesn't seem any useful.

I've actually seen quite a few blogs which use images for black&white diagrams or charts, so the suggested feature would be useful for swapping the foreground/background colors of those kinds of images.

**Comment by adityatelange** [comment]
@kdkasad The person is referring to images in config. i.e. label logo and/or pfp from profile mode only.
Inline images with markdown will won't be affected.

**Comment by adityatelange** [comment]
> > Image is an image, why would anyone put dark/light variants ? Doesn't seem any useful.
> 
> I've actually seen quite a few blogs which use images for black&white diagrams or charts, so the suggested feature would be useful for swapping the foreground/background colors of those kinds of images.

The feature you are mentioning is different from that in issue imo.

**Comment by IntModifier** [comment]
As a person with a use case for this I would also like to see this possibility.  The logo image I want to use by default is primarily black with some white detail. However when the theme switches to dark you can barely see it, so it would be nice if I could specify an inverse (primary white with black detail) image for the profile mode logo if dark mode is selected. 

Currently just forcing light theme and disabling switcher.

**Comment by adityatelange** [comment]
@IntModifier can you share the website ? Lemme have a look

**Comment by IntModifier** [comment]
@adityatelange  sorry for the delay my page is started here: https://intmodifier.github.io/

**Comment by martomi** [comment]
I also think the feature makes sense in some workflows.It can make use of a similar pattern to how Hugo handles [alternative static directories for multi-language sites](https://ciechanow.ski/cameras-and-lenses/#recording-light). In the same way, it'd be convenient to be able to define `static_light` and `static_dark` and load images based on the chosen style.

**Comment by kdkasad** [comment]
> I also think the feature makes sense in some workflows. It can make use of a similar pattern to how Hugo handles [alternative static directories for multi-language sites](https://ciechanow.ski/cameras-and-lenses/#recording-light). E.g. define `static_light` and `static_dark` and load images based on the chosen style.

While this is an interesting idea, I don't think it would work. The reason is each language-specific site has hard-coded links to its own static directory. However, the light/dark theme is controllable at run time (i.e. when the site is viewed), so there would have to be some JavaScript which goes through every `href=` and `src=` attribute and substitutes the right directory.

That, or there would have to be 2 separate site trees for the light and dark variants. At that point, just add two different languages, make both of them the same actual content language, but with different names (preferably `light` and `dark`), and force the theme to light for one and dark for the other.

**Comment by bruno-garcia** [comment]
Would it be possible to load it by convention? 

```
resources:
- src: 'davidfowl-nuget-package-debug-dark.png'
- src: 'davidfowl-nuget-package-debug-light.png'
- src: 'dnx-release-build-pack-dark.png'
- src: 'dnx-release-build-pack-light.png'
```

There could be a map of such files and it would generate a map and JS to toggle between the `src` of those.
I'm using screenshots of GitHub which have dark theme and light theme (that changes automatically if you toggle the OS theme) and it doesn't look great to throw a white image on a dark theme site:

![image](https://user-images.githubusercontent.com/1633368/119232653-fbd82d80-baf3-11eb-99fb-058e764193ae.png)

**Comment by joaopgrassi** [comment]
I tried something, but it's not awesome. https://github.com/joaopgrassi/blog/commit/a1719d0de39cd27ee0d69f8f79e9cd2b06738621

I have this shortcode to add a custom "look" for my images. The idea is that I add the "dark themed image" to the page's resources and then inside my shortcode I check if I have it AND if I'm currently in dark mode (via css class in the body). Then I just replace the image `src`. 

The point now where it breaks is that if I change the site theme at the top, the image ofc doesn't change. One solution is to register a click there inside the shortcode and react on it. But.. not sure it's great since you could have a lot of event listeners if you have several images on a page..

**Comment by erahn-safejump** [comment]
Piling in here to say that this would be very useful to be able to change images used in the markdown based on the theme being light/dark.
