### ISSUE TITLE
expand share icons and supported networks for sharing

### ISSUE THREAD

**Issue by 1000283** [adityatelange/hugo-PaperMod#87]
Just as the **author** can add 34 icons to diverse social platforms s/he might have an account on; it would be interesting if a **visitor** was able to share a post onto those same platforms.

Also, there are other fediverse networks out there, such as 

- [pleroma](https://pleroma.social/) and [misskey](https://join.misskey.page/en/) for microblogging (like twitter);
- [funkwhale](https://funkwhale.audio/) for audio (soundcloud, spotify);
- [peertube](https://peer.tube/) for video (youtube, lbry);
- [pixelfed](https://pixelfed.org/) for images (instagram);
- [GNU social](https://gnusocial.network/), [friendica](https://friendi.ca/), [hubzilla](https://hubzilla.frama.io/core/) and [diaspora*](https://diaspora.social/) for general social networking (facebook).

**Comment by adityatelange** [comment]
@1000283 Sure we can add those platforms to the list.
The problem is getting the SVG icons style match with those of currently added. 

Also it depends on whether the platform has a share-URL, which it parses so as to generate a post.
While in case of social-icons we aren't dependent on platform, it is just a link to it !
